### ISSUE TITLE
Previously signed Chatoyant Staff

### ISSUE THREAD

**Issue by Armikazie** [myera/issues#138] opened 2016-06-01 10:41 UTC
Hiyas! Its your friendly neighborhood Aias here!

So I found out while I was away on my hiatus that the AH was wiped and all the chat staffs had their signatures removed. I can always restock the AH with more crafted gear/mats/food but my signed chat staff...

I leveled the craft, and I farmed the eggs, just so I could sign my name on my very own. And as my first chat staff, it was never meant to be augmented and stands as a testament to my pride as an artisan on Era!

Besides, I'd like for everyone to know they can come to me for all their crafting needs free of charge as long as they have the mats! If they see my signature, they know who to go to... It's always worked in the past.

If it's not too much trouble,
Aias

**Comment by Armikazie** [comment] 2016-06-01 11:37
Been looking through all of my old screenshots for proof of my own signed staff but only found one I signed for an ls mate.

http://imgur.com/5geTT7G

Was trying to get more ppl to play whm at the time xD

**Comment by Armikazie** [comment] 2016-06-02 03:51
I have just been informed by Kev about the signature situation and now completely understand. Thank you Kev and to Warp for passing it on. I won't troubling you anymore on the matter. 

Of course I hope it all works out with DSP but I'll be making those SS's of what I've already crafted/signed just in case. You've put my mind at ease just knowing and I'll be more prepared if it happens again later on. Just don't forget to inform the rest of the server when the time comes!

Best wishes,
Aias

**Comment by Rihce** [comment] 2016-06-03 03:22
I'm not going to close this though because its a work in progress still. 
- Kevin

**Comment by LocoFFEra** [comment] 2016-06-05 02:46
This has been resolved.

**Comment by Rihce** [comment] 2016-06-05 15:22
did warp recode sigs? if not this is still an open issue.

**Comment by LocoFFEra** [comment] 2016-06-05 17:37
He did, I confirmed this by checking Aias & Paiine's old Chatoyant's that had the wrong/removed sigs.

**Closed by LocoFFEra** 2016-06-05 17:37 UTC
